.DEFAULT_GOAL := help
PROJECTNAME=$(shell basename "$(PWD)")
SOURCES=$(sort $(wildcard ./src/*.rs ./src/**/*.rs))

OS_NAME=$(shell uname | tr '[:upper:]' '[:lower:]')
PATH := $(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/bin:$(PATH)
LIB_NAME := p4d_rust_binding

ANDROID_AARCH64_LINKER=$(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/bin/aarch64-linux-android29-clang
ANDROID_ARMV7_LINKER=$(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/bin/armv7a-linux-androideabi29-clang
ANDROID_I686_LINKER=$(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/bin/i686-linux-android29-clang

SHELL := /bin/bash
LIB_BUILD_TARGET := lib$(LIB_NAME).so



# ##############################################################################
# # GENERAL
# ##############################################################################

.PHONY: help
help: makefile
	@echo
	@echo " Available actions in "$(PROJECTNAME)":"
	@echo
	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e 's/^/ /'
	@echo

## init: Install missing dependencies.
.PHONY: init
init:
	rustup target add aarch64-apple-ios x86_64-apple-ios
	rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android
	@if [ $$(uname) == "Darwin" ] ; then cargo install cargo-lipo ; fi
	cargo install cbindgen

## :

# ##############################################################################
# # RECIPES
# ##############################################################################

## all: Compile iOS, Android and bindings targets
all: ios android bindings copy_ios copy_android

## ios: Compile the iOS universal library
ios: target/universal/release/$(LIB_BUILD_TARGET)

target/universal/release/$(LIB_BUILD_TARGET): $(SOURCES) ndk-home
	@if [ $$(uname) == "Darwin" ] ; then \
		cargo lipo --release ; \
		else echo "Skipping iOS compilation on $$(uname)" ; \
	fi

## android: Compile the android targets (arm64, armv7 and i686)
android: target/aarch64-linux-android/release/$(LIB_BUILD_TARGET) target/armv7-linux-androideabi/release/$(LIB_BUILD_TARGET) target/i686-linux-android/release/$(LIB_BUILD_TARGET)

target/aarch64-linux-android/release/$(LIB_BUILD_TARGET): $(SOURCES) ndk-home
	CC_aarch64_linux_android=$(ANDROID_AARCH64_LINKER) \
	CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$(ANDROID_AARCH64_LINKER) \
		cargo build --target aarch64-linux-android --release

target/armv7-linux-androideabi/release/$(LIB_BUILD_TARGET): $(SOURCES) ndk-home
	CC_armv7_linux_androideabi=$(ANDROID_ARMV7_LINKER) \
	CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=$(ANDROID_ARMV7_LINKER) \
		cargo build --target armv7-linux-androideabi --release

target/i686-linux-android/release/$(LIB_BUILD_TARGET): $(SOURCES) ndk-home
	CC_i686_linux_android=$(ANDROID_I686_LINKER) \
	CARGO_TARGET_I686_LINUX_ANDROID_LINKER=$(ANDROID_I686_LINKER) \
		cargo  build --target i686-linux-android --release

.PHONY: ndk-home
ndk-home:
	@if [ ! -d "${ANDROID_NDK_HOME}" ] ; then \
		echo "Error: Please, set the ANDROID_NDK_HOME env variable to point to your NDK folder" ; \
		exit 1 ; \
	fi

## bindings: Generate the .h file for iOS
bindings: target/bindings.h

target/bindings.h: $(SOURCES)
	# cbindgen $^ -c cbindgen.toml | grep -v \#include | uniq > $@
	cbindgen ./src/lib.rs -c cbindgen.toml | grep -v \#include | uniq | cat > target/bindings.h
	cat ./target/bindings.h >> ../ios/Classes/SubstrateSignFlutterPlugin.h

# ##############################################################################
# # OTHER
# ##############################################################################

## clean:
.PHONY: clean
clean:
	cargo clean
	rm -f target/bindings.h target/bindings.src.h

## test:
.PHONY: test
test:
	cargo test

## copy_ios:
.PHONY: copy_ios
copy_ios:
	cp "./target/universal/release/lib$(LIB_NAME).a" "../ios/lib$(LIB_NAME).a"

## copy_android:
.PHONY: copy_android
copy_android:
	mkdir -p "../android/src/main/jniLibs/arm64-v8a"
	cp "./target/aarch64-linux-android/release/lib${LIB_NAME}.so" "../android/src/main/jniLibs/arm64-v8a/lib$(LIB_NAME).so";
	mkdir -p "../android/src/main/jniLibs/armeabi-v7a";
	cp "./target/armv7-linux-androideabi/release/lib${LIB_NAME}.so" "../android/src/main/jniLibs/armeabi-v7a/lib$(LIB_NAME).so";
	mkdir -p "../android/src/main/jniLibs/x86";
	cp "./target/i686-linux-android/release/lib${LIB_NAME}.so" "../android/src/main/jniLibs/x86/lib$(LIB_NAME).so";
	
	